api_platform:
  formats:
    json: ['application/json']
    jsonld: ['application/ld+json']
    html: ['text/html']
    multipart: ['multipart/form-data']

  oauth:
    # To enable or disable OAuth.
    enabled: true

    # The OAuth client ID.
    clientId: 'dcac236605196772f81c877f62f13467'

    # The OAuth client secret.
    clientSecret: 'f16ceeab3f0d269473e7e9010faea54daaac02a85dc4512fe1443dbeb6ce02123b090c1adb7b41ffd3252972183b2125dc6c887ac6cb7f2953e1c181c12b3bc8'

    # The OAuth type.
    type: 'oauth2'

    # The OAuth flow grant type.
    flow: 'password'

    # The OAuth token url.
    tokenUrl: '/token'

    # The OAuth authentication url.
    authorizationUrl: '/oauth/v2/auth'

    # The OAuth scopes.
    scopes: []